### PR TITLE
Added commands and fixed some errors

### PR DESCRIPTION
**Pull request by geriko7**
I have added 3 commands:
-Low Ammo , Target Neutralized , KIA/Lost one

Fixed 2 command:
-Wait for me
-Take Cover

### CODE REVIEW

**Comment by SPARTAN563** [comment]
Hi @geriko7,
Thanks for this (y) I'll see if I can get my local build environment setup again and will package a new release as soon as that's done.

**Comment by geriko7** [comment]
Hey there,
Thanks for putting it in, but in the latest release it's not working.
I didn't find anything and I don't know a lot about it, so can you take a look at the files?

**Comment by SPARTAN563** [comment]
Certainly, sorry about that - will check as soon as I get home after work

**Comment by geriko7** [comment]
Thank you! Looking forward to your reply!

**Comment by SPARTAN563** [comment]
Hi @geriko7,
I unfortunately wasn't able to reproduce any crash (I assume that you're referring to a crash when you say "it's not working"). I've included a couple of other fixes and tweaks to try and track down any crashes if that is the case - so if you wouldn't mind trying out [v0.2.8](https://github.com/Mpstark/articulate/releases/tag/v0.2.8) I'd appreciate it.

Regards,
Benjamin

**Comment by geriko7** [comment]
Thanks for your reply!

Actually, the Hungarian translation was only one of the issues. The other was, that when I said any commands that I've put in the software, wasn't working. It didn't understand my pronunciations. I've tried all of these commands. Did it work for you?

Best Regards,
Gary Raven

**Comment by SPARTAN563** [comment]
Commands appear to work for me, however you need to remember to say a unit group before the command itself, so "all, be advised, low fuel" should work. That's a limitation of the grammar used currently, it's of the form `[subject] [command] (direction)`.

Before the project sort of closed down, Michael and I were looking at implementing a custom grammar syntax which would have allowed greater flexibility here, but unfortunately we never got around to finishing it (it's a rather complex task to undertake, especially when you need to bind it to keystroke sequences, and while trying to keep it compact).

**Comment by geriko7** [comment]
Yeah, yeah... Thank you. Now it's working. 
Anyway, thank you for fixing the grammar problems in the commands!
It'd be good to make a custom grammar syntax, because in status actions It's bad to say the [subject] first, it'd be good to make to say only command.
Soon I'll go and work on it.

**Pull request merged**
